import fs from 'fs';
const core = fs.readFileSync('node_modules/three/build/three.core.js', 'utf8');
const re = /from\s+['"]([^'"]+)['"]/g;
const s = new Set();
let m;
while ((m = re.exec(core))) s.add(m[1]);
console.log('core imports', [...s]);
console.log('core len', core.length);
const mod = fs.readFileSync('node_modules/three/build/three.module.js', 'utf8');
const s2 = new Set();
while ((m = re.exec(mod))) s2.add(m[1]);
console.log('module imports', [...s2]);
